### ISSUE TITLE
Can't load model checkpoints

### ISSUE THREAD

**Issue by Gokulnath-Sourirajan** [phantrdat/cvpr20-scatter-text-recognizer#6]
I had downloaded the checkpoint of non-sensitive model but looks like the model architecture and the checkpoints are dissimilar. Has anyone faced the same issue? Any help would be much appreciated!

python3 demo.py --saved_model scatter-case-non-sensitive.pth --sensitive --image_folder ../../svt1
loading pretrained model from scatter-case-non-sensitive.pth
Traceback (most recent call last):
  File "demo.py", line 137, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    model.load_state_dict(torch.load(opt.saved_model, map_location=device))
  File "/home/gokul/MMOCR/mmocr_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.Refiner.decoder.weight: copying a param with shape torch.Size([38, 512]) from checkpoint, the shape in current model is torch.Size([96, 512]).
        size mismatch for module.Refiner.decoder.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for module.ctx_block1.selective_decoder.second_attention.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([2048, 1062]) from checkpoint, the shape in current model is torch.Size([2048, 1120]).
        size mismatch for module.ctx_block1.selective_decoder.second_attention.generator.weight: copying a param with shape torch.Size([38, 512]) from checkpoint, the shape in current model is torch.Size([96, 512]).
        size mismatch for module.ctx_block1.selective_decoder.second_attention.generator.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for module.ctx_block2.selective_decoder.second_attention.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([2048, 1062]) from checkpoint, the shape in current model is torch.Size([2048, 1120]).
        size mismatch for module.ctx_block2.selective_decoder.second_attention.generator.weight: copying a param with shape torch.Size([38, 512]) from checkpoint, the shape in current model is torch.Size([96, 512]).
        size mismatch for module.ctx_block2.selective_decoder.second_attention.generator.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for module.ctx_block3.selective_decoder.second_attention.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([2048, 1062]) from checkpoint, the shape in current model is torch.Size([2048, 1120]).
        size mismatch for module.ctx_block3.selective_decoder.second_attention.generator.weight: copying a param with shape torch.Size([38, 512]) from checkpoint, the shape in current model is torch.Size([96, 512]).
        size mismatch for module.ctx_block3.selective_decoder.second_attention.generator.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for module.ctx_block4.selective_decoder.second_attention.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([2048, 1062]) from checkpoint, the shape in current model is torch.Size([2048, 1120]).
        size mismatch for module.ctx_block4.selective_decoder.second_attention.generator.weight: copying a param with shape torch.Size([38, 512]) from checkpoint, the shape in current model is torch.Size([96, 512]).
        size mismatch for module.ctx_block4.selective_decoder.second_attention.generator.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for module.ctx_block5.selective_decoder.second_attention.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([2048, 1062]) from checkpoint, the shape in current model is torch.Size([2048, 1120]).
        size mismatch for module.ctx_block5.selective_decoder.second_attention.generator.weight: copying a param with shape torch.Size([38, 512]) from checkpoint, the shape in current model is torch.Size([96, 512]).
        size mismatch for module.ctx_block5.selective_decoder.second_attention.generator.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in

**Comment by relh** [comment]
I see this issue too.

Also the non-sensitive checkpoint takes in --sensitive as a command line argument and the sensitive one doesn't take in --sensitive as an argument in the example snippet.

**Comment by relh** [comment]
It seems to only be the case non sensitive model that doesn't load from the checkpoint correctly, try the other model

**Comment by phantrdat** [comment]
Hi friends. Sorry for my late response. I have updated the code so it works now. Thanks.
